In [62]:
import pandas as pd
import re

df=pd.read_csv("train.csv")

mots_inutiles = set([
    "i","me","my","myself","we","our","ours","ourselves",
    "you","your","yours","yourself","yourselves",
    "he","him","his","himself",
    "she","her","hers","herself",
    "it","its","itself",
    "they","them","their","theirs","themselves",
    "what","which","who","whom","this","that","these","those",
    "am","is","are","was","were","be","been","being",
    "have","has","had","do","does","did",
    "a","an","the","and","or","but","if","because","as",
    "until","while","of","at","by","for","with","about","against",
    "between","into","through","during","before","after","above","below",
    "to","from","up","down","in","out","on","off","over","under",
    "again","further","then","once","get", "just", "like", "can", "not","know",
    "want","time","how","when","now","all","feel", "really", "things", "just",
    "like","very", "too", "lot", "there", "back",
    "even", "every", "years", "told",
    "going", "still", "one", "now","will"
])
contractions = {
    "don't":"do not",
    "can't":"can not",
    "i'm":"i am",
    "it's":"it is",
    "i've":"i have",
    "you're":"you are",
    "we're":"we are",
    "they're":"they are"
}
def preprocess(texte):
    if pd.isna(texte):
        return []

    texte=texte.lower()
    for k,v in contractions.items():
        texte=texte.replace(k, v)
    texte=re.sub(r'[^\w\s]',' ',texte)

    tokens=texte.split()

    tokens=[t for t in tokens if t not in mots_inutiles]
    tokens=[t for t in tokens if len(t) > 2]

    return tokens

df['patient_clean'] = df.iloc[:,0].apply(preprocess)
df['therapist_clean'] = df.iloc[:,1].apply(preprocess)
nb_patients=df.iloc[:,0].nunique()
print("Patients uniques:", nb_patients)
nb_therapeutes=df.iloc[:,1].nunique()
print("Thérapeutes uniques:", nb_therapeutes)


echange_moyens = len(df) / nb_patients
print("Échanges moyens par patient:", echange_moyens)

Patients uniques: 995
Thérapeutes uniques: 2479
Échanges moyens par patient: 3.52964824120603

In [63]:
from collections import Counter

tout_mots=[mot for tokens in df['patient_clean'] for mot in tokens]
freq = Counter(tout_mots)

print(freq.most_common(20))

[('never', 623), ('always', 509), ('relationship', 504), ('should', 461), ('think', 442), ('people', 434), ('love', 428), ('anxiety', 412), ('other', 406), ('boyfriend', 396), ('help', 392), ('counseling', 390), ('life', 377), ('having', 353), ('issues', 344), ('more', 331), ('need', 331), ('sex', 330), ('family', 326), ('depression', 320)]

In [64]:
pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.3.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.7.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cpu)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.24.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (0.1.2)

In [65]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

df['patient_text'] = df['patient_clean'].apply(lambda x: " ".join(x))

df = df.drop_duplicates(subset="patient_text")
df = df.drop_duplicates(subset="patient_clean")

tfidf = TfidfVectorizer(max_features=2000)

X = tfidf.fit_transform(df['patient_text'])
kmeans = KMeans(n_clusters=8, random_state=42)
df['cluster_tfidf'] = kmeans.fit_predict(X)
print(df[['patient_text', 'cluster_tfidf']].head(10))
print(df['cluster_tfidf'].value_counts())
print(df[df['cluster_tfidf'] == 0]['patient_text'].head(10))
order_centroids = kmeans.cluster_centers_.argsort()[:, ::-1]
terms = tfidf.get_feature_names_out()

for i in range(8):
    print(f"Cluster {i}")
    top_words = [terms[ind] for ind in order_centroids[i, :10]]
    print(top_words)

                                         patient_text  cluster_tfidf
0   some feelings barely sleep nothing think worth...              2
23  many issues address history sexual abuse breas...              6
70  feeling more more month started having trouble...              1
72  facing severe depression anxiety distracts can...              6
81                        place where content day day              3
84  severe problem major several minor operations ...              6
86  suffer adult adhd anxiety disorder depression ...              0
89  few ago making love wife known reason lost ere...              0
95  struggle depression well pretty intense mood s...              1
99  self harm stop awhile see something sad depres...              5
cluster_tfidf
6    197
1    138
5     97
0     91
2     83
3     82
7     77
4     66
Name: count, dtype: int64
86     suffer adult adhd anxiety disorder depression ...
89     few ago making love wife known reason lost ere...
146    dealing depression anxiety number medication l...
171                constantly bad mood energy depression
183    think adult life making depressed often sleep ...
190    need deal depression tell anyone deal depressi...
200    never able talk parents parents sixties teenag...
211    hard depressed parents getting divorce bad hap...
240    both parents committed suicide together found ...
254    think may suffer depression affecting life sle...
Name: patient_text, dtype: object
Cluster 0
['help', 'need', 'wife', 'bad', 'depression', 'making', 'divorce', 'child', 'past', 'life']
Cluster 1
['love', 'more', 'relationship', 'guy', 'think', 'dating', 'says', 'boyfriend', 'talking', 'someone']
Cluster 2
['wrong', 'nothing', 'happy', 'always', 'way', 'friends', 'say', 'doing', 'anything', 'why']
Cluster 3
['said', 'night', 'girlfriend', 'day', 'life', 'reason', 'help', 'husband', 'family', 'says']
Cluster 4
['people', 'scared', 'talk', 'school', 'always', 'ever', 'someone', 'meet', 'since', 'afraid']
Cluster 5
['something', 'never', 'girl', 'tell', 'stop', 'much', 'should', 'first', 'lied', 'say']
Cluster 6
['boyfriend', 'mother', 'always', 'mom', 'anxiety', 'keep', 'child', 'other', 'should', 'parents']
Cluster 7
['thoughts', 'having', 'why', 'people', 'make', 'cry', 'find', 'anxiety', 'often', 'start']

In [66]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

embed_model = SentenceTransformer('all-MiniLM-L6-v2')
words = ["anxiety", "depression", "stress", "sleep"]
word_embeddings = embed_model.encode(words)
sim_matrix = cosine_similarity(word_embeddings)

all_words = list(set(sum(df['patient_clean'], [])))

embeddings = embed_model.encode(all_words)

def most_similar(word, words, embeddings, top_n=10):
    import numpy as np
    from sklearn.metrics.pairwise import cosine_similarity
    idx=words.index(word)
    sims=cosine_similarity([embeddings[idx]], embeddings)[0]
    top_idx=sims.argsort()[::-1][1:top_n+1]
    return [(words[i], round(float(sims[i]), 3))
        for i in top_idx]

result=most_similar("depression", all_words, embeddings)
pd.DataFrame(result, columns=["word", "similarity"])

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

          word  similarity
0   depressive       0.885
1    depressed       0.861
2  psychiatric       0.703
3      suicide       0.661
4   depressing       0.661
5  depressants       0.638
6       misery       0.631
7    happiness       0.627
8      unhappy       0.616
9     suicidal       0.611

In [67]:
result2=most_similar("anxiety", all_words, embeddings)
pd.DataFrame(result2, columns=["word", "similarity"])

            word  similarity
0        anxious       0.855
1      anxieties       0.715
2        nervous       0.674
3           fear       0.669
4          fears       0.663
5      terrified       0.624
6          panic       0.620
7    psychiatric       0.601
8       paranoid       0.600
9  uncomfortable       0.592

In [68]:
result3=most_similar("stress", all_words, embeddings)
pd.DataFrame(result3, columns=["word", "similarity"])

          word  similarity
0    stressing       0.929
1     stressed       0.928
2    stressors       0.876
3     stresses       0.862
4     stressor       0.836
5    stressful       0.792
6      tension       0.639
7      anxiety       0.586
8      anxious       0.585
9  frustration       0.570

In [69]:
result4=most_similar("sleep", all_words, embeddings)
pd.DataFrame(result4, columns=["word", "similarity"])

       word  similarity
0  sleeping       0.906
1    sleeps       0.894
2    asleep       0.806
3     slept       0.786
4       nap       0.761
5    waking       0.660
6  dreaming       0.641
7       bed       0.637
8     wakes       0.635
9     awake       0.619

In [70]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
vectorizer = CountVectorizer(max_features=2000)
X = vectorizer.fit_transform(df['patient_text'])

In [71]:
lda = LatentDirichletAllocation(n_components=5, random_state=42)
lda.fit(X)
mots=vectorizer.get_feature_names_out()

for i, sujet in enumerate(lda.components_):
    print(f"Sujet {i}")
    print([mots[i] for i in sujet.argsort()[-10:]])

Sujet 0
['day', 'three', 'anxiety', 'people', 'friends', 'think', 'doesn', 'help', 'disorder', 'family']
Sujet 1
['school', 'friend', 'day', 'home', 'never', 'family', 'together', 'boyfriend', 'said', 'love']
Sujet 2
['away', 'life', 'girlfriend', 'never', 'sex', 'boyfriend', 'always', 'relationship', 'mom', 'other']
Sujet 3
['talk', 'having', 'make', 'help', 'always', 'love', 'think', 'life', 'boyfriend', 'never']
Sujet 4
['more', 'relationship', 'see', 'sex', 'says', 'husband', 'always', 'should', 'think', 'past']